<a href="https://colab.research.google.com/github/Raaj-4320/Kaggle/blob/main/ASSIGNMENT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'is-the-traffic-collision-fatal:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-competitions-data%2Fkaggle-v2%2F70315%2F7736702%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240314%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240314T202233Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D00abc84a5912676476021cef3eff20ac8e0f12121c7cf54a99930292f516379c8ab7fa629ff77564926438994e7d72cb7c184cbc637ca1944b0ea523c744f0d77e0ee41ba475283860b4906aa21bdd81419b3b39401713a916841ec0657a940e204b6d2d5bce61ce365218993e4b914dba92fa8a94ee7a1cb17be8e4f865256815789722f333605cd90d8e10573ef70205c20bc9fbcf27829fee51a903296bc4518876eceb8a7b34c19e7de7a7b8eed4d1b71275755d0419a928f7f447f670a365936d11343b7bc8944179e365598a9f5ebc53368ccd005d6c7c0a200f6537f048ec7db9c904fd86445043121f56eecb37d7c9309f3ab395a0e782df0b7f6896'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')

Downloading is-the-traffic-collision-fatal, 814014 bytes compressed
[==================================================] 814014 bytes downloaded
Downloaded and uncompressed: is-the-traffic-collision-fatal
Data source import complete.

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/is-the-traffic-collision-fatal/Test.csv
/kaggle/input/is-the-traffic-collision-fatal/Train.csv

# Minimum Requirements Met
(5 marks)
-------------------------------------------------------------------------------------------------
## All requirements met.
### Applied multiple (>=4) Machine learning Techniques.
(1 mark)

### Data preprocessing using Sklearn pipeline present in the solution.
(1 mark)

### Presented all the metrics (MSE, RMSE, MAE, R-Square, Adjusted R-Square (for Regression) Precision, Recall, Accuracy, AUC, F1 Score (For Classification). Include Test Set Results from Kaggle.
(1 mark)

### Grid Search / Randomized Search / Bayesian Optimization
(1 mark)

### Feature Importance shown for all algorithms.
(1 mark)

## Coding practices
(5 Marks)
### The code is well-commented, and well explained for all the steps throughout the notebook especially in areas that you found difficult to program.(1 Marks)

### Proper use of Variable names, following the best practices.
(1 Mark)

### Use of Python Methods (definitions and classes) to avoid repetition of code.
(3 Marks)

## Presentation skills and Time taken (5 marks)

### The Group showed great presentation skills and story telling skills.
(3 Marks)

### The Group finished their presentation within the 10 minutes deadline.
(1 Mark)

### The Group answered all the questions correctly, asked by the instructor.
(1 Marks)

In [4]:
df = pd.read_csv("/kaggle/input/is-the-traffic-collision-fatal/Train.csv")
dfts = pd.read_csv("/kaggle/input/is-the-traffic-collision-fatal/Test.csv")

In [5]:
df

,INDEX_,ACCNUM,YEAR,DATE,TIME,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,...,AG_DRIV,REDLIGHT,ALCOHOL,DISABILITY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,DIVISION,ObjectId
0,3387730,892658.0,2006,2006/03/11 05:00:00+00,852,BLOOR ST W,DUNDAS ST W,NaN,Major Arterial,Toronto and East York,...,Yes,NaN,NaN,NaN,88,High Park North,88,High Park North (88),D11,1
1,3387731,892658.0,2006,2006/03/11 05:00:00+00,852,BLOOR ST W,DUNDAS ST W,NaN,Major Arterial,Toronto and East York,...,Yes,NaN,NaN,NaN,88,High Park North,88,High Park North (88),D11,2
2,3388101,892810.0,2006,2006/03/11 05:00:00+00,915,MORNINGSIDE AVE,SHEPPARD AVE E,NaN,Major Arterial,Scarborough,...,Yes,Yes,NaN,NaN,146,Malvern East,132,Malvern (132),D42,3
3,3389067,893184.0,2006,2006/01/01 05:00:00+00,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,...,Yes,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,4
4,3388102,892810.0,2006,2006/03/11 05:00:00+00,915,MORNINGSIDE AVE,SHEPPARD AVE E,NaN,Major Arterial,Scarborough,...,Yes,Yes,NaN,NaN,146,Malvern East,132,Malvern (132),D42,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,81474608,NaN,2018,2018/04/26 04:00:00+00,1942,ISLINGTON AVE,ALBION RD,NaN,Major Arterial,Etobicoke York,...,Yes,NaN,NaN,NaN,3,Thistletown-Beaumond Heights,3,Thistletown-Beaumond Heights (3),D23,14996
14996,81474609,NaN,2018,2018/04/26 04:00:00+00,1942,ISLINGTON AVE,ALBION RD,NaN,Major Arterial,Etobicoke York,...,Yes,NaN,NaN,NaN,3,Thistletown-Beaumond Heights,3,Thistletown-Beaumond Heights (3),D23,14997
14997,81474610,NaN,2018,2018/04/26 04:00:00+00,1942,ISLINGTON AVE,ALBION RD,NaN,Major Arterial,Etobicoke York,...,Yes,NaN,NaN,NaN,3,Thistletown-Beaumond Heights,3,Thistletown-Beaumond Heights (3),D23,14998
14998,81474611,NaN,2018,2018/04/26 04:00:00+00,1942,ISLINGTON AVE,ALBION RD,NaN,Major Arterial,Etobicoke York,...,Yes,NaN,NaN,NaN,3,Thistletown-Beaumond Heights,3,Thistletown-Beaumond Heights (3),D23,14999
14999,81474612,NaN,2018,2018/04/26 04:00:00+00,1942,ISLINGTON AVE,ALBION RD,NaN,Major Arterial,Etobicoke York,...,Yes,NaN,NaN,NaN,3,Thistletown-Beaumond Heights,3,Thistletown-Beaumond Heights (3),D23,15000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 55 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   INDEX_             15000 non-null  int64
 1   ACCNUM             11302 non-null  float64
 2   YEAR               15000 non-null  int64
 3   DATE               15000 non-null  object
 4   TIME               15000 non-null  int64
 5   STREET1            15000 non-null  object
 6   STREET2            13657 non-null  object
 7   OFFSET             1928 non-null   object
 8   ROAD_CLASS         14643 non-null  object
 9   DISTRICT           14986 non-null  object
 10  WARDNUM            15000 non-null  int64
 11  LATITUDE           15000 non-null  float64
 12  LONGITUDE          15000 non-null  float64
 13  LOCCOORD           14910 non-null  object
 14  ACCLOC             9550 non-null   object
 15  TRAFFCTL           14971 non-null  object
 16  VISIBILITY         14986 non-null  object
 17  LIGHT              15000 non-null  object
 18  RDSFCOND           14981 non-null  object
 19  ACCLASS            15000 non-null  object
 20  IMPACTYPE          15000 non-null  object
 21  INVTYPE            14990 non-null  object
 22  INVAGE             15000 non-null  object
 23  INJURY             13394 non-null  object
 24  FATAL_NO           593 non-null    float64
 25  INITDIR            10502 non-null  object
 26  VEHTYPE            12945 non-null  object
 27  MANOEUVER          8486 non-null   object
 28  DRIVACT            7425 non-null   object
 29  DRIVCOND           7421 non-null   object
 30  PEDTYPE            2460 non-null   object
 31  PEDACT             2450 non-null   object
 32  PEDCOND            2445 non-null   object
 33  CYCLISTYPE         635 non-null    object
 34  CYCACT             621 non-null    object
 35  CYCCOND            620 non-null    object
 36  PEDESTRIAN         5966 non-null   object
 37  CYCLIST            1578 non-null   object
 38  AUTOMOBILE         13672 non-null  object
 39  MOTORCYCLE         1162 non-null   object
 40  TRUCK              933 non-null    object
 41  TRSN_CITY_VEH      923 non-null    object
 42  EMERG_VEH          19 non-null     object
 43  PASSENGER          5633 non-null   object
 44  SPEEDING           1998 non-null   object
 45  AG_DRIV            7696 non-null   object
 46  REDLIGHT           1275 non-null   object
 47  ALCOHOL            672 non-null    object
 48  DISABILITY         420 non-null    object
 49  HOOD_158           15000 non-null  object
 50  NEIGHBOURHOOD_158  15000 non-null  object
 51  HOOD_140           15000 non-null  object
 52  NEIGHBOURHOOD_140  15000 non-null  object
 53  DIVISION           15000 non-null  object
 54  ObjectId           15000 non-null  int64
dtypes: float64(4), int64(5), object(46)
memory usage: 6.3+ MB